ALTER TABLE "players" ADD COLUMN IF NOT EXISTS "firstName" TEXT;
ALTER TABLE "players" ADD COLUMN IF NOT EXISTS "lastName" TEXT;
ALTER TABLE "players" ADD COLUMN IF NOT EXISTS "birthDate" TIMESTAMP(3);
ALTER TABLE "players" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "players" ADD COLUMN IF NOT EXISTS "nationality" TEXT;
