ALTER TABLE "players"
  ADD COLUMN "attPct" INTEGER NOT NULL DEFAULT 17,
  ADD COLUMN "difPct" INTEGER NOT NULL DEFAULT 17,
  ADD COLUMN "murPct" INTEGER NOT NULL DEFAULT 17,
  ADD COLUMN "alzPct" INTEGER NOT NULL DEFAULT 17,
  ADD COLUMN "ricPct" INTEGER NOT NULL DEFAULT 16,
  ADD COLUMN "staPct" INTEGER NOT NULL DEFAULT 16;
